### ISSUE TITLE
Ready for signature e-mail has HTML

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#59] opened 2018-05-14 21:30 UTC
In "Ready for signature" email:
  <b>Signature(s) requested from: </b>Services account / Single Sign-On URL:
  https://esh-docdbdev.fnal.gov/cgi-bin/sso/ShowDocument?docid=3458
  (take out <b> </b>?, add blank line before "Services account / Single Sign-on URL")

**Comment by lauramengel** [comment] 2018-05-30 17:49
Fixed. Closing issue. Ready for Signature email gives
the user better instructions now and does not have
any html tags in it.

**Closed by lauramengel** 2018-05-30 17:49 UTC
Labels: Medium

**Comment by lauramengel** [comment] 2018-05-30 17:52
Maybe I should not have closed this since it says above:
- "ericvaandering moved this from To Do to Laura in 8.8.9 release 
- Add security routines for FNAL SSO #25

But I have confirmed "Ready for signature" message is fixed in FNALSSO branch.

**Comment by ericvaandering** [comment] 2018-05-30 18:06
No, that's fine. "Laura" is everything that waiting for your confirmation.
